---

name: Build and release

on:
  push:
    tags:        
      - '**'   

jobs:
  # build package, make release on github and upload to pypi when a new tag is pushed
  # see https://github.com/RegioHelden/github-reusable-workflows/blob/main/.github/workflows/python-build-and-release.yaml
  build-and-release:
    name: Build and release
    uses: regiohelden/github-reusable-workflows/.github/workflows/python-build-and-release.yaml@main
