---

name: Check pull request

on:
  push:
    # on all branches except for main
    branches:
      - '**'
      - '!main'
  # when labels are added or removed
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  # lint code for errors
  # see https://github.com/RegioHelden/github-reusable-workflows/blob/main/.github/workflows/python-ruff.yaml
  lint:
    name: Lint
    uses: RegioHelden/github-reusable-workflows/.github/workflows/python-ruff.yaml@main
    with:
      ruff-version: "0.9.9"
      python-version: "3.12"

  # make sure the pull request matches our guidelines like having at least one label assigned
  # see https://github.com/RegioHelden/github-reusable-workflows/blob/main/.github/workflows/check-pull-request.yaml
  check-pull-request:
    name: Check pull request
    needs:
      - lint
    uses: RegioHelden/github-reusable-workflows/.github/workflows/check-pull-request.yaml@main
